### PR TITLE
Added support for regular pksnod string.

### PR DESCRIPTION
**Pull request by johansvard**
- added config for commandline test tool for checking both stub and local version of stub.
- Added method in stub that returns the pnod string, with upper case änd replaced å, ä and ö
- Added method in Pknodfetcher for getting pknod from server.
- refactored somewhat in PknodFetcher, making both regular and plus implementation use the same method

### CODE REVIEW

**Comment by albinsunnanbo** [comment]
Any particular reason you have changed the TestPersonsPuData file?

**Comment by johansvard** [comment]
No, not really. I should probably have reverted that change, since it was done as a bad try to fix something else…

**Comment by albinsunnanbo** [comment]
If you revert the file and commit with "amend" you'll overwrite the existing commit and all traces of the mishap will be gone

**Comment by albinsunnanbo** [comment]
Merged with minor fixes

**Pull request closed without merging**
